export const GET_EVENTS_REQUESTED = 'GET_EVENTS_REQUESTED';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED';

export const GET_ARTISTS_REQUESTED = 'GET_ARTISTS_REQUESTED';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_FAILED = 'GET_ARTISTS_FAILED';

export const GET_VENUES_REQUESTED = 'GET_VENUES_REQUESTED';
export const GET_VENUES_SUCCESS = 'GET_VENUES_SUCCESS';
export const GET_VENUES_FAILED = 'GET_VENUES_FAILED';